# Generated by Django 4.0.2 on 2022-02-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=255)),
                ('pressure', models.DecimalField(decimal_places=2, max_digits=255)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=255)),
                ('description', models.CharField(max_length=250)),
                ('time', models.DecimalField(decimal_places=2, max_digits=255)),
                ('wind', models.CharField(max_length=250)),
                ('icon', models.CharField(max_length=250)),
            ],
        ),
    ]
