# Generated by Django 4.0.2 on 2022-02-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecastApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='humidity',
            field=models.DecimalField(decimal_places=1, max_digits=255),
        ),
        migrations.AlterField(
            model_name='weather',
            name='pressure',
            field=models.DecimalField(decimal_places=1, max_digits=255),
        ),
        migrations.AlterField(
            model_name='weather',
            name='temperature',
            field=models.DecimalField(decimal_places=1, max_digits=255),
        ),
        migrations.AlterField(
            model_name='weather',
            name='time',
            field=models.DecimalField(decimal_places=4, max_digits=255),
        ),
    ]
